# Generated by Django 3.1.2 on 2020-10-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regextool', '0002_auto_20201028_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='avres',
            new_name='result',
        ),
    ]
