# Generated by Django 3.1.2 on 2020-10-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querytool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueryTool',
            new_name='User',
        ),
    ]
